version: "3.8"
services:
  filefinder:
    build: .
    image: filefinder:latest
    container_name: filefinder
    volumes:
      - ./data:/data             # your files and patterns.txt
      - ./found_files:/found_files  # optional: where to save the found data (if you use --save-full-folder)
    environment:
      - TZ=Europe/Moscow         # or your time zone
    command: >
      --pattern-file /data/patterns.txt
      --whitelist txt,log
      --archives
      --threads 8
      /data
